### ISSUE TITLE
Explain what this is for?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [RadPad/react-markup-service#3]
I read the whole README and it isn't clear what problem this solves. Maybe a full example? Show what code someone can _remove_ if they use your module?

**Comment by jcblw** [comment]
Thanks for the feedback! I actually was thinking about this just yesterday.

Just to answer your question (I'll do a better write up for the README to close this ticket)

#### Reason we use it

So the reason why we use something like this @ RadPad, is that our site was built using something other than node 😢 . It was built on Rails and our frontend is React. We wanted to do some server side rendering in our views (which were currently being handled by Rails). 

We initially tried to use something like [react-stdio](https://github.com/mjackson/react-stdio), but the startup of the node process was to slow. We decided to create a micro service for this. Essentially the service creates a api to which we could request markup for a component that we were using in the webpage. On request to the webpage (to Rails), we make a request to this Node service to get the markup for the component, then place that into the markup of the view. It was alot faster.

That worked well, but complicated the deployment process due to having to: copying over files, compiling files again, and race conditions with some configuration we were loading from our api.

Making the service work this way helped: removing duplicate babel configurations, simplifying our deployment process, and brought the service closer to the other application which removed latency.

---

Hopefully, that helps answer your question. I'll see if I can setup a simple repo that can show off the use case better.

**Comment by jcblw** [comment]
closing now via #4
